import Skill_Rating from "../Business_Logic/SkillRating.js";

const UI = {

    /*** GENERAL ***/

    body: document.body,

    /*** HEADER ***/

    // Header Video 
    header: document.querySelector("header"),
    header_vid: document.querySelector("header video"),
    nav_container: document.querySelector(".nav-container"),
    top_nav: document.querySelector(".top-header-nav"),
    bot_nav: document.querySelector(".bot-header-nav"),
    body_placeholder: document.querySelector("body .placeholder-div"),
    header_empty_div: document.querySelector("header .empty-div"),
    scroll_indicator: document.querySelector("#my-bar"),
    active_lists: document.querySelectorAll(".bot-header-nav .nav-item"),
    active_link: document.querySelector("a.active"),

    /*** HOME SECTION ***/

    intro_msg: document.querySelector(".intro"),
    welcome: document.querySelector(".welcome"),
    text_wrapper_ml13: document.querySelector('.ml13'),
    
    // Generated by the shape divider app (remember to change class name if changing divider using app)
    header_divider: document.querySelector(".custom-shape-divider-bottom-1612032701"),

    /*** ABOUT SECTION ***/

    about_summary_wrapper: document.querySelector(".about-section .summary-wrapper"),
    my_age: document.querySelector("[data-age='my-age']"),
    summary_containers: document.querySelectorAll(".summary-container"),
    summary_btn: document.querySelector("[data-id='summary-btn']"),

    /*** SERVICES SECTION ***/

    my_carousel_prev_btn: document.querySelector(".services-section .my-carousel-btn-prev"),
    my_carousel_next_btn: document.querySelector(".services-section .my-carousel-btn-next"),
    my_carousel_wrapper: document.querySelector(".my-carousel-wrapper"),
    my_carousel_content: document.querySelector(".my-carousel-content"),
    my_carousel_items: document.querySelectorAll(".my-carousel-item"),

    /*** TOOLS & TECHNOLOGIES SECTION ***/ 

    skill_ratings: document.querySelectorAll(".skill-rating"),
    skill_ratings_beginner: document.querySelectorAll(".skill-rating-beginner"),
    skill_ratings_novice: document.querySelectorAll(".skill-rating-novice"),
    skill_ratings_intermediate: document.querySelectorAll(".skill-rating-intermediate"),
    skill_ratings_advanced: document.querySelectorAll(".skill-rating-advanced"),
    skill_ratings_expert: document.querySelectorAll(".skill-rating-expert"),

    /*** PROJECT SECTION ***/ 

    dev_project_gallery: document.getElementById("dev-project-gallery"),
    dev_project_overview: document.getElementById("dev-project-overview"),
    dev_project_gallery_btns: document.querySelectorAll("button[data-dev-project]"),
    client_project_gallery: document.getElementById("client-project-gallery"),
    client_project_gallery: document.getElementById("client-project-overview"),
    client_project_gallery_btns: document.querySelectorAll("button[data-client-project]"),

    /*** CONTACT ME SECTION ***/

    /* Formspree */

    valid_feedback_fname: document.querySelector(".valid-feedback.valid-feedback-fname"),
    valid_feedback_lname: document.querySelector(".valid-feedback.valid-feedback-lname"),
    valid_feedback_email: document.querySelector(".valid-feedback.valid-feedback-email"),
    valid_feedback_message: document.querySelector(".valid-feedback.valid-feedback-message"),
    invalid_feedback_fname: document.querySelector(".invalid-feedback.invalid-feedback-fname"),
    invalid_feedback_lname: document.querySelector(".invalid-feedback.invalid-feedback-lname"),
    invalid_feedback_email: document.querySelector(".invalid-feedback.invalid-feedback-email"),
    invalid_feedback_message: document.querySelector(".invalid-feedback.invalid-feedback-message"),

    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    forms_need_validation: document.querySelectorAll('.needs-validation'),

    // Get the form elements defined in your form HTML
    my_form: document.getElementById("my-form"),
    my_form_button: document.getElementById("my-form-button"),
    my_form_status: document.getElementById("my-form-status"),
    grecaptcha: document.getElementsByClassName("g-recaptcha"),

    create_script(...srcs) {

        srcs.forEach(src => {

            const script = document.createElement("script");
            script.src = src;
            script.setAttribute("async", "async");
            this.body.appendChild(script);    
        });
    },

    shrink_header() {

        // On scroll, shrinks header and expands body, pauses video, changes to static bg and adjusts height of placeholder elements for smooth transition
        this.body.classList.remove("will-change-height");
        this.nav_container.classList.add("row", "justify-content-between", "nav-container-sticky");
        this.top_nav.classList.add("col-2");
        this.bot_nav.classList.add("col-10");
        this.header_empty_div.classList.add("d-none");
        this.header_divider.classList.add("d-none");
        //this.top_nav.style.height = "100%";
        //this.bot_nav.style.height = "100%";
        //this.nav_container.style.height = "6rem";
        this.top_nav.style.height = "auto";
        this.bot_nav.style.height = "auto";
        this.nav_container.style.height = "auto";
        this.body_placeholder.style.height = "46.875rem";
        this.body_placeholder.classList.replace("invisible","visible");
        this.body_placeholder.classList.replace("placeholder-div-reveal-start","placeholder-div-reveal-end");
        this.header_vid.classList.add("d-none");
        this.header_vid.pause();
        this.header.style.background = "linear-gradient(rgba(31,111,139,0.95), rgba(31,111,139,0.95)), url('') no-repeat fixed 100% 100%";
        
        // On scroll, hides introduction msg and removes top padding from welcome section below
        this.intro_msg.classList.add("h-0");
        this.welcome.classList.remove("pt-custom-1");                    
    },

    expand_header() {

        // Returns header and body to initial states when scrolled to the top
        this.body.classList.add("will-change-height");
        this.nav_container.classList.remove("row", "justify-content-between", "nav-container-sticky");
        this.top_nav.classList.remove("col-2");
        this.bot_nav.classList.remove("col-10");
        this.header_empty_div.classList.remove("d-none");
        this.header_divider.classList.remove("d-none");
        //this.top_nav.style.height = "initial";
        //this.bot_nav.style.height = "initial";
        //this.nav_container.style.height = "25rem";
        this.top_nav.style.height = "auto";
        this.bot_nav.style.height = "auto";
        this.nav_container.style.height = "auto";
        this.body_placeholder.style.height = "0";
        this.body_placeholder.classList.replace("visible","invisible");
        this.body_placeholder.classList.replace("placeholder-div-reveal-end","placeholder-div-reveal-start");
        this.header_vid.classList.remove("d-none");
        this.header_vid.play();

        // Returns introduction msg and welcome section to initial state when scrolled to the top
        this.intro_msg.classList.remove("h-0");
        this.welcome.classList.add("pt-custom-1");
    },

    replace_vid_bg() {

        // To replace the header video bg when it ends
        this.header.style.background = "linear-gradient(rgba(31,111,139,0.8), rgba(0,0,0,0.6)), url('/img/laptop.jpg') no-repeat fixed";
        this.header.style.backgroundSize = "cover";
        this.header.style.transition = "background 3s ease-in-out";
    },

    animate_letters() {

        // Wrap every letter in a span
        this.text_wrapper_ml13.innerHTML = this.text_wrapper_ml13.textContent.replace(/\S/g, "<span class='letter'>$&</span>");
        
        anime.timeline({loop: true})
        .add({

            targets: '.ml13 .letter',
            translateY: [100,0],
            translateZ: 0,
            opacity: [0,1],
            easing: "easeOutExpo",
            duration: 600,
            delay: (el, i) => 300 + 30 * i,
        })
        .add({

            targets: '.ml13 .letter',
            translateY: [0,-100],
            opacity: [1,0],
            easing: "easeInExpo",
            duration: 600,
            delay: (el, i) => 6000 + 30 * i,
        });
    },

    change_about_info() {

        if(this.summary_containers[1].classList.contains("d-none")) {

            this.about_summary_wrapper.classList.add("opacity-0");

            setTimeout(() => {
                
                this.summary_containers[0].classList.add("d-none", "opacity-0");
                this.summary_containers[1].classList.remove("d-none", "opacity-0");
                this.summary_btn.innerHTML = "Go Back";
            }, 205);

            setTimeout(() => {

                this.about_summary_wrapper.classList.remove("opacity-0");
            }, 350);
        } else if(this.summary_containers[0].classList.contains("d-none")) {

            this.about_summary_wrapper.classList.add("opacity-0");

            setTimeout(() => {
                
                this.summary_containers[1].classList.add("d-none", "opacity-0");
                this.summary_containers[0].classList.remove("d-none", "opacity-0");
                this.summary_btn.innerHTML = "Learn More";
            }, 205);

            setTimeout(() => {

                this.about_summary_wrapper.classList.remove("opacity-0");
            }, 350);
        };
    },

    grow_btn_onclick(btn, size, time) {

        btn.style.transform = `scale(${size})`;

        setTimeout(() => {
            
            btn.style.transform = "initial";
        }, time);
    },

    scroll_horizontally(el, px) {

        el.scrollLeft += px;
    },

    scroll_start(el, px_limit) {

        if(el.scrollLeft >= (el.scrollWidth - el.clientWidth - px_limit))
        {
            el.scrollLeft = 0;
        };
    },

    scroll_end(el, px_limit) {

        if(el.scrollLeft <= px_limit)
        {
            el.scrollLeft = (el.scrollWidth - el.clientWidth);
        };
    },

    populate_skill_rating(Skill) {

        this.skill_ratings_beginner.forEach(rating_div => {

            rating_div.innerHTML = Skill.getRating("beginner");
        });
        
        this.skill_ratings_novice.forEach(rating_div => {
            
            rating_div.innerHTML = Skill.getRating("novice");
        });
        
        this.skill_ratings_intermediate.forEach(rating_div => {

            rating_div.innerHTML = Skill.getRating("intermediate");
        });
        
        this.skill_ratings_advanced.forEach(rating_div => {

            rating_div.innerHTML = Skill.getRating("advanced");
        });

        this.skill_ratings_expert.forEach(rating_div => {

            rating_div.innerHTML = Skill.getRating("expert");
        });
    },

    display_form_validation_msg() {

        // Updates UI with different success validation messages after failure to submit correctly
        if(this.invalid_feedback_fname && window.getComputedStyle(this.invalid_feedback_fname).display != "none") {
    
            this.valid_feedback_fname.innerHTML = "Nice! You remembered your first name!";
        };

        if(this.invalid_feedback_lname && window.getComputedStyle(this.invalid_feedback_lname).display != "none") {

            this.valid_feedback_lname.innerHTML = "So you do have a last name...";
        };

        if(this.invalid_feedback_email && window.getComputedStyle(this.invalid_feedback_email).display != "none") {

            this.valid_feedback_email.innerHTML = "Much better...please ensure that the spelling of your email is correct";
        };

        if(this.invalid_feedback_message && window.getComputedStyle(this.invalid_feedback_message).display != "none") {

            this.valid_feedback_message.innerHTML = "How did you forget the most important part? Oh well, at least it's fine now...";
        };
    }
};

export default UI;