[[redirects]]
  from = "https://darnellnoel.netlify.app/*"
  to = "https://www.darnellnoel.dev/"
  status = 301
  force = true

[[redirects]]
  from = "http://darnellnoel.netlify.app/*"
  to = "https://www.darnellnoel.dev/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.darnellnoel.netlify.app/*"
  to = "https://www.darnellnoel.dev/"
  status = 301
  force = true

[[redirects]]
  from = "http://www.darnellnoel.netlify.app/*"
  to = "https://www.darnellnoel.dev/"
  status = 301
  force = true